### ISSUE TITLE
Best practise for legacy classes

### ISSUE THREAD

**Issue by fritzmg** [contao/docs#100]
As discussed in slack, we should provide a best-practise documentation for the handling of legacy classes. e.g. that they should all reside in a single sub-namespace, like `Contao`, so that you can easily exclude them from service resource loading like so:

```yaml
services:
    App\:
        resource: ../src
        exclude: ../src{Contao,DependencyInjection,Resources,Entity}
```

Background: if you accidentally auto-register a class that extends from `\Contao\System`, you will run into a fatal error during container building.

**Comment by m-vo** [comment]
see https://github.com/symfony/symfony/issues/34053

**Comment by m-vo** [comment]
Services are a concept that works well with composition + interfaces. The legacy code requires you to inherit from all sorts of classes instead. Plus: constructor injection often isn't possible.

Considering this I think a **separate sub namespace** (that is excluded from service resource loading) for these classes should be the best practice no matter the outcome of the related Symfony issue. The same is true for tests and coverage. I would exclude these classes as well as they aren't testable for the same reason.

So you would end up with `App\Contao\Widget\MyWidget` instead of `App\Widget\MyWidget` for example.

**Comment by fritzmg** [comment]
I would like to get the approval of @contao/developers on this. So in the future, the recommended namespaces would be:

* `App\Contao\Model`
* `App\Contao\Widget`
* `App\Contao\ContentElement`
* `App\Contao\FrontendModule`

etc. 

This would also need to be reflected in the Skeleton Bundle by @leofeyer

**Comment by leofeyer** [comment]
No, there must not be a `Contao` namespace.

* `App\Model`
* `App\Widget`
* `App\ContentElement`
* `App\FrontendModule`

**Comment by Toflar** [comment]
It depends. I don't think I would like to give a recommendation here. People may still use their brains 😄
If I have an app where I only extend Contao then I would not add this subnamespace. It's useless. If I have an app that consists of content management and an API I would probably make a difference on top level and have additional `Contao` and `Api` namespaces.

**Comment by fritzmg** [comment]
> No, there must not be a `Contao` namespace.

Then the service resource-loading would need to be defined as

```yml
services:
    App\:
        resource: ../src
        exclude: ../src{Widget,Model,ContentElement,FrontendModule,DependencyInjection,Resources,Entity}
```

Plus any other subnamespace of legacy Contao classes.
