### ISSUE TITLE
Issue with CSS custom properties and the search field

### ISSUE THREAD

**Issue by netzarbeiter** [contao/docs#1524]
dark mode (Safari) blue colour (expected colour orange) and search field

![Image](https://github.com/user-attachments/assets/25a86142-2985-4931-896c-7c2101e19fc0)

light mode (Firfox) blue colour (expected colour orange)

![Image](https://github.com/user-attachments/assets/da20c126-ac0e-4b64-87a8-4bcdb48877c3)

**Comment by fritzmg** [comment]
Does it work properly on https://mcshelby.github.io/hugo-theme-relearn/index.html?

**Comment by netzarbeiter** [comment]
dark mode (Safari)

![Image](https://github.com/user-attachments/assets/9980a371-4fa6-4a67-bbf3-b4844385033d)

light mode (Safari)

![Image](https://github.com/user-attachments/assets/9b348ed5-46ce-4028-a5a5-c173237adc70)

**Comment by fritzmg** [comment]
Seems to look correct, yeah.

I am afraid this will have to be debugged by someone with access to Safari.

**Comment by ausi** [comment]
It looks like the following code block causes Safari to ignore all the rules that are following inside the (nested) @ media block.

```css
.algolia-searchbox input[type=search]::-moz-placeholder {
    color:rgba(255, 255, 255, .6)
}
.algolia-searchbox input[type=search]:-moz-placeholder {
    color:rgba(255, 255, 255, .6)
}
.algolia-searchbox input[type=search]:-ms-input-placeholder {
    color:rgba(255, 255, 255, .6)
}
```

in *format-html.min.css* line 216.

IMO we should delete these two rules and instead just use the `::placeholder` as this is supported in all major browsers.
