### ISSUE TITLE
Deaktivierung/Aktivierung Websitesuche

### ISSUE THREAD

**Issue by frontendschlampe** [contao/docs#288]
seit Contao 4.9 sind die Einstellungen zur Website-Suche

- Suche aktivieren
- Geschützte Seiten indizieren

nicht mehr im Backend einstellbar.

Leider ist hier https://docs.contao.org/manual/de/system/einstellungen/#website-suche noch der Weg über die Einstellungen im Backend beschrieben.

Ab Contao 4.9 erfolgt das sicherlich über eine `config.yml`.
Wie sind die Einträge dafür?

**Comment by fritzmg** [comment]
Solltest du über

```
vendor/bin/contao-console config:dump-reference contao
```

sehen. https://docs.contao.org/manual/de/system/einstellungen/#config-yml

```yml
contao:
    search:
        default_indexer:
            enable:               true
        index_protected:      false
```

Habe den config:reference-dump in 20d8803203ae5aaf847f3a6e49c188150f4a571e aktualisiert.
