### ISSUE TITLE
Clarify service annotation for bundles

### ISSUE THREAD

**Issue by mwoelke** [contao/docs#557]
Whenever service annotations are mentioned in the current developer docs, it reads like nothing but the service tag is required for it to work. Examples:

https://docs.contao.org/dev/framework/hooks/#using-annotations
https://docs.contao.org/dev/framework/content-elements/#annotation

This however is not correct for bundles, where the services.yml needs some adjustment as well. This can lead to confusion and should be adressed imo. I was personally frustrated with annotations not working until I found the following core-issue:

https://github.com/contao/contao/issues/1449

The author seemed to assume that nothing but the annotation is required as well.

Personally, I think that one specific page for service annotation setup would be ideal. This page could then be linked whenever the topic is mentioned.

**Comment by fritzmg** [comment]
> Whenever service annotations are mentioned in the current developer docs, it reads like nothing but the service tag is required for it to work.

That is true for the application (based on the Contao Managed Edition), which the docs mainly cover.

> This however is not correct for bundles, where the services.yml needs some adjustment as well.

That is mentioned in the _Getting Started_ article on [_Creating an Extension_](https://docs.contao.org/dev/getting-started/extension/#service-configuration).

**Comment by mwoelke** [comment]
Yes, I found this as well. After reading it I assumed that simply adding
```
services:
    _defaults:
        autoconfigure: true
```
will do the trick. 

However, as yourself explained in the linked issue above, you have to implicitly add your class as well like so:
```
services:
    _defaults:
        autoconfigure: true
    Acme\FooBundle\EventListener\BarListener: 
        tags: ['terminal42_service_annotation']
```

or

```
services:
    _defaults:
        autoconfigure: true
    Acme\FooBundle\EventListener\BarListener: ~
```

This may seem obvious to developers more familiar with Symfony, but it wasn't to me.

**Comment by fritzmg** [comment]
> Yes, I found this as well. After reading it I assumed that simply adding
> 
> ```
> services:
>     _defaults:
>         autoconfigure: true
> ```
> 
> will do the trick.

That is the case 👍 



> However, as yourself explained in the linked issue above, you have to implicitly add your class as well like so:
> 
> ```
> services:
>     _defaults:
>         autoconfigure: true
>     Acme\FooBundle\EventListener\BarListener: 
>         tags: ['terminal42_service_annotation']
> ```
> 
> or
> 
> ```
> services:
>     _defaults:
>         autoconfigure: true
>     Acme\FooBundle\EventListener\BarListener: ~
> ```
> 
> This may seem obvious to developers more familiar with Symfony, but it wasn't to me.

That is mentioned in the _Getting Started_ article [_Starting your Development_](https://docs.contao.org/dev/getting-started/starting-development/#autoloading-services-and-actions). If you are still unfamiliar with either Contao 4 or Symfony, then reading through the Getting Started articles is essential.

**Comment by mwoelke** [comment]
The text and examples given in the _Getting Started_ article all refer to classes in the _App\\_ namespace where behaviour is slightly different. 

Maybe I'm wrong, but from my understanding in order to register a service annotation in the App\\ namespace the following code is sufficient (taken from the same article):

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
```

However, I don't see any mentioning about having to pass the _['terminal42_service_annotation']_ tag when **not** developing in the App\ namespace.

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
  Acme\FooBundle\EventListener\BarListener: 
    tags: ['terminal42_service_annotation']

```

**Comment by fritzmg** [comment]
You don't need to do that, if you enabled auto configuration. See https://docs.contao.org/dev/getting-started/extension/#service-configuration and the README of https://github.com/terminal42/service-annotation-bundle

**Comment by fritzmg** [comment]
Although, is that still true without the `ServiceAnnotationInterface` @aschempp? The new README only briefly mentions auto configuration.

**Comment by fritzmg** [comment]
As far as I tested, tagging the service is not necessary.

@mwoelke given the information above, do you have any suggestions on what to improve in the docs, if necessary?

**Comment by mwoelke** [comment]
I'll try to set up a public bundle to reproduce the tagging issue I had.

Hopefully this weekend :)

This will either draw attention to some problem with service tags  _or_ some mistake I made. Probably the latter... 😉

**Comment by mwoelke** [comment]
First of all: Thank you for bearing out with me on this one :)

I've now setup an example plugin to show the behavior I mentioned: 
https://github.com/mwoelke/contao-serviceannotation-example

Uncommentating these two lines in services.yml adds the content element to the container for me, otherwise it's not working:

```
services:
    #MWoelke\ExampleServiceAnnotationBundle\Controller\ContentElement\ExampleContentElementController:
    #    tags: ['terminal42_service_annotation']
    _defaults:
        autoconfigure: true 
        autowire: true
  [...]
```
Maybe someone can have a look at the bundle and point out why the tagging is necessary.
Thank you for your time!

**Comment by fritzmg** [comment]
The problem is that you did not register your service. Thus the service cannot be tagged automatically - since there is no service to be tagged to begin with 😉.

In your case, the `services.yml` could look like this for example:

```yml
services:
    _defaults:
        autoconfigure: true 

    MWoelke\ExampleServiceAnnotationBundle\Controller\ContentElement\ExampleContentElementController: ~
```

Since you were also planning on using auto-wiring ([which you should not do for public bundles](https://symfony.com/doc/current/service_container/autowiring.html#public-and-reusable-bundles)), you could also automatically register your services:

```yml
services:
    _defaults:
        autoconfigure: true 
        autowire: true

    MWoelke\ExampleServiceAnnotationBundle\:
        resource: ../../
```
