### ISSUE TITLE
Document new config for the list of allowed protocols

### ISSUE THREAD

**Issue by MarkejN** [contao/docs#840]
With https://github.com/contao/contao/pull/3488 the following config is going to be added:
```yaml
contao:
    sanitizer:
        allowed_url_protocols:

            # Defaults:
            - https
            - http
            - ftp
            - mailto
            - tel
            - data
            - skype
            - whatsapp
```
Versions: probably 4.9.25+ and 4.13+
